/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/3HkqbSuezFo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Activity } from "lucide-react"
import Link from "next/link"

export function Landingpage() {
  return (
    <div>
      <header className="flex items-center justify-between h-16 px-4 md:px-6 bg-white ">
        <Link href="#" className="flex items-center" prefetch={false}>
        <Activity className="w-8 font-extrabold" />
          
          <span className="sr-only">InV</span>
        </Link>
        <Link
          href="/commingsoon"
          className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
          prefetch={false}
        >
          Contact Us
        </Link>
      </header>
      <section className="w-full h-[80vh] bg-[url('/hero-bg.jpg')] bg-cover bg-center flex items-center justify-center mt-4 py-12 md:py-24">
        <div className="container px-4 md:px-6 text-center space-y-6">
          <h1 className="text-2xl md:text-4xl font-bold text-black drop-shadow-md">
          Unified Inventory Management for Shopify, WooCommerce & WhatsApp
          </h1>
          <div className="w-full flex flex-col justify-center items-center p-2 overflow-hidden">
          <img className="max-w-md sm:max-w-xl rounded-lg  w-full" src="./shopify.webp"/>
          </div>
          
          <p className="text-lg md:text-xl text-black/90 max-w-3xl mx-auto drop-shadow-md">
          Manage your Shopify, WooCommerce, and WhatsApp inventories from one dashboard. Sync, track, and simplify your e-commerce operations with ease.
          </p>
          <Link
            href="/commingsoon"
            className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
            prefetch={false}
          >
            Get Started
          </Link>
        </div>
      </section>
    </div>
  )
}

function MountainIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
